# Generated by Django 4.2.7 on 2023-11-07 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danielAgency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='trip_cover'),
        ),
    ]
